const digitalFeatureGroups = [
  { tab: 'Quản lý tài chính toàn diện', panels: [
    ['Gắn kết gia đình cùng Abby Family', 'Giải pháp tài chính dành riêng cho gia đình, giúp con làm quen với việc quản lý tiền bạc một cách chủ động', 'https://abbank.vn/frontend/images/khach-hang-ca-nhan/abby-family.png'],
    ['Chuyển tiền nhanh, thanh toán gọn', 'Tự động nhắc thanh toán hàng tháng, tạm biệt nỗi lo hóa đơn quá hạn', 'https://abbank.vn/uploads/images/2026/02/06/fast-transfer-6985bbf4c3e22.png'],
    ['Rút gốc một phần từ khoản tiết kiệm online', 'Giữ nguyên lãi phần còn lại, không giới hạn số lần rút, thao tác ngay trên ứng dụng', 'https://abbank.vn/uploads/images/2026/02/06/withdraw-online-saving-6985bd545a192.png']
  ]},
  { tab: 'Tiện ích phong phú', panels: [
    ['Âm thanh thông báo', 'Đọc to số tiền nhận được, giúp bạn biết có giao dịch ngay cả khi không cầm điện thoại', 'https://abbank.vn/frontend/images/khach-hang-ca-nhan/am-thanh-thong-bao.png'],
    ['Dán mã QR', 'Tạm biệt nỗi lo “ảnh rác” khi chỉ cần sao chép mã QR và dán ảnh để chuyển tiền', 'https://abbank.vn/uploads/images/2026/02/06/dan-ma-qr-6985bd233e793.png'],
    ['Cá nhân hóa hình nền', 'Tự do thể hiện phong cách riêng qua hình nền ứng dụng, từ màu sắc đến chủ đề', 'https://abbank.vn/frontend/images/khach-hang-ca-nhan/ca-nhan-hoa-hinh-nen.png']
  ]},
  { tab: 'Bảo mật vượt trội', panels: [['Bảo mật FIDO tiên tiến', 'Thay thế mật khẩu bằng tương tác sinh trắc học duy nhất của bạn. Tăng khả năng nhận diện người dùng, ràng buộc thiết bị với danh tính của bạn và dùng được ngay khi cài ABBANK.', 'https://abbank.vn/uploads/images/2026/02/06/nhs-bao-mat-6985ba25f4070.png']] }
];

const digitalFeatureTabs = digitalFeatureGroups.map((group, index) => `<button type="button" role="tab" class="digital-feature-tab${index === 2 ? ' is-active' : ''}" data-feature-tab="${index}" aria-selected="${index === 2}">${group.tab}</button>`).join('');
const digitalFeatureMarkup = digitalFeatureGroups.map((group, groupIndex) => {
  if (groupIndex === 2) {
    return `<div class="digital-feature-panel is-active" data-feature-panel="2"><div class="digital-feature-cards digital-security-cards"><article><div><h3>Ứng dụng ABBANK mới sử dụng công nghệ bảo mật FIDO (Fast IDentity Online) tiên tiến.</h3><ul><li><img src="https://abbank.vn/frontend/images/khach-hang-ca-nhan/success.png" alt="success"><span>Thay thế mật khẩu bằng tương tác sinh trắc học duy nhất của bạn</span></li><li><img src="https://abbank.vn/frontend/images/khach-hang-ca-nhan/success.png" alt="success"><span>Tăng khả năng nhận diện người dùng, ràng buộc thiết bị với danh tính của bạn</span></li><li><img src="https://abbank.vn/frontend/images/khach-hang-ca-nhan/success.png" alt="success"><span>Dùng được ngay khi cài ABBANK, thao tác dễ dàng và tương thích với nhiều thiết bị Samsung, Apple...</span></li></ul><p>Đây là công nghệ được phát triển bởi FIDO Alliance - hiệp hội gồm các công ty công nghệ, nhà phát triển hàng đầu như Amazon, Apple, Google, American Express, Dell, Intel</p></div><img src="${group.panels[0][2]}" alt="Bảo mật vượt trội"></article></div></div>`;
  }
  return `<div class="digital-feature-panel${groupIndex === 2 ? ' is-active' : ''}" data-feature-panel="${groupIndex}"><div class="digital-feature-cards">${group.panels.map((panel, index) => `<article><img src="${panel[2]}" alt="${panel[0]}"><div><span>0${index + 1}</span><h3>${panel[0]}</h3><p>${panel[1]}</p></div></article>`).join('')}</div></div>`;
}).join('');

V.digital = () => `<div class="digital-page">
  <section class="digital-hero"><div class="wrap"><div class="digital-hero-copy"><span class="eyebrow">ABBANK DIGITAL</span><h1>Ngân hàng số<br><em>trong tầm tay bạn</em></h1><p>Ứng dụng ABBANK giúp bạn tự tin quản lý tài chính và ra quyết định chi tiêu sáng suốt thông qua các đề xuất cá nhân hóa.</p><div class="btns"><a class="btn" href="https://onelink.to/xfyvzn" target="_blank" rel="noopener">Tải ứng dụng</a><a class="btn o" href="#digital-faq">Tìm hiểu thêm</a></div></div><div class="digital-hero-art"><img src="https://abbank.vn/frontend/images/khach-hang-ca-nhan/digital-banking.png" alt="Ứng dụng ABBANK Digital"></div></div></section>
  <section class="digital-highlights"><div class="wrap"><div class="digital-intro"><h2>Điều tuyệt vời nào đang chờ đón bạn?</h2><p>Ứng dụng ABBANK giúp bạn tự tin quản lý tài chính và ra quyết định chi tiêu sáng suốt thông qua các đề xuất cá nhân hóa.</p></div><div class="digital-feature-tabs" role="tablist">${digitalFeatureTabs}</div><div class="digital-feature-grid">${digitalFeatureMarkup}</div></div></section>
  <section class="digital-steps"><div class="wrap"><div class="digital-intro"><h2>Cài đặt nhanh chỉ trong 3 bước</h2></div><div class="digital-step-grid"><article><img src="https://abbank.vn/uploads/images/2026/02/06/download-app-6985bc7ceb896.png" alt="Tải ứng dụng ABBANK"><div><b>1</b><h3>Tải ứng dụng ABBANK trên App Store hoặc Google Play</h3><p>*Lưu ý: Vui lòng không tải ứng dụng thông qua các đường link không nằm trong thông báo chính thức của ABBANK</p></div></article><article><img src="https://abbank.vn/frontend/images/khach-hang-ca-nhan/authen-step.png" alt="Xác thực sinh trắc học"><div><b>2</b><h3>Xác thực sinh trắc học</h3><p>Chọn “Tôi chưa có tài khoản” và tiến hành các bước xác thực sinh trắc học</p></div></article><article><img src="https://abbank.vn/frontend/images/khach-hang-ca-nhan/add-information-and-complete.png" alt="Bổ sung thông tin"><div><b>3</b><h3>Bổ sung thông tin và hoàn thành</h3><p>Thêm thông tin cá nhân, chọn tên đăng nhập và hoàn tất bước đăng nhập</p></div></article></div><a class="digital-video" href="https://www.youtube.com/watch?v=iHiyxIq8SVA" target="_blank" rel="noopener"><span class="digital-play">▶</span>Xem video hướng dẫn</a></div></section>
  <section class="digital-offers"><div class="wrap"><div class="digital-intro"><h2>Ưu đãi dành cho bạn</h2><p>Hãy trải nghiệm ngay ứng dụng ABBANK mới và nhận muôn vàn ưu đãi.</p></div><div class="digital-offer-grid"><a href="https://abbank.vn/dich-vu/abby-family.html" target="_blank" rel="noopener"><img src="https://abbank.vn/frontend/images/khach-hang-ca-nhan/abby-family-di.png" alt="Abby Family đi, chờ chi!"><span class="tag">ƯU ĐÃI</span><h3>Abby Family đi, chờ chi!</h3></a><a href="https://abbank.vn/uu-dai/sam-loa-loc-vang-ron-rang-uu-dai.html" target="_blank" rel="noopener"><img src="https://abbank.vn/frontend/images/khach-hang-ca-nhan/sam-loa-loc-vang.png" alt="Sắm loa lộc vang - rộn ràng ưu đãi"><span class="tag">ƯU ĐÃI</span><h3>Sắm loa lộc vang – rộn ràng ưu đãi</h3></a><a href="https://abbank.vn/thong-tin/lai-suat-tiet-kiem-vnd.html" target="_blank" rel="noopener"><img src="https://abbank.vn/frontend/images/khach-hang-ca-nhan/lai-suat.png" alt="Tiết kiệm Online, hưởng lãi tốt hơn"><span class="tag">ƯU ĐÃI</span><h3>Tiết kiệm Online, hưởng lãi tốt hơn</h3></a></div></div></section>
  <section class="digital-faq" id="digital-faq"><div class="wrap"><div class="digital-faq-copy"><div class="digital-intro"><h2>Câu hỏi thường gặp</h2></div><details><summary>Thông tin hướng dẫn sử dụng ứng dụng ABBANK</summary><p>Khám phá hướng dẫn và các tiện ích nổi bật trong ứng dụng ABBANK Digital.</p></details><details><summary>Ứng dụng ABB Ditizen hiện tại còn được sử dụng không?</summary><p>Vui lòng cập nhật ứng dụng ABBANK chính thức để sử dụng các dịch vụ ngân hàng số mới nhất.</p></details><details><summary>Điều kiện để bắt đầu sử dụng ứng dụng ABBANK?</summary><p>Bạn cần giấy tờ tùy thân còn hiệu lực và số điện thoại đăng ký chính chủ.</p></details></div><img class="digital-support" src="https://abbank.vn/frontend/images/khach-hang-ca-nhan/support.png" alt="Bạn cần hỗ trợ thêm"></div></section>
  <section class="digital-contact"><div class="wrap"><img class="digital-contact-art" src="https://abbank.vn/frontend/images/khach-hang-ca-nhan/digital-banking.png" alt="Ứng dụng ABBANK"><div class="digital-contact-copy"><div class="digital-contact-download"><img src="https://abbank.vn/frontend/images/khach-hang-ca-nhan/qr.png" alt="QR tải ứng dụng ABBANK"><div><h2>Trải nghiệm ngân hàng số ABBANK ngay hôm nay</h2><div class="digital-store-links"><a href="https://onelink.to/xfyvzn" target="_blank" rel="noopener"><img src="https://abbank.vn/frontend/images/khach-hang-ca-nhan/ios-download.png" alt="App Store"></a><a href="https://onelink.to/xfyvzn" target="_blank" rel="noopener"><img src="https://abbank.vn/frontend/images/khach-hang-ca-nhan/google-play-download.png" alt="Google Play"></a></div></div></div><div class="digital-contact-grid"><div><b>Hotline 24/7</b><a href="tel:18001159">1800.1159 hoặc 028.38365.365</a></div><div><b>Chi nhánh</b><a href="#contact/app">Xem danh sách chi nhánh</a></div><div><b>Kết nối</b><div class="digital-social-links"><a href="https://zalo.me/3397825272211662938" target="_blank" rel="noopener"><img src="https://abbank.vn/frontend/images/khach-hang-ca-nhan/zalo.png" alt="Zalo"></a><a href="https://www.facebook.com/nganhanganbinh/" target="_blank" rel="noopener"><img src="https://abbank.vn/frontend/images/khach-hang-ca-nhan/facebook.png" alt="Facebook"></a></div></div></div></div></div></section>
</div>`;

document.addEventListener('click', event => {
  const tab = event.target.closest('[data-feature-tab]');
  if (!tab) return;
  const page = tab.closest('.digital-page');
  page.querySelectorAll('[data-feature-tab]').forEach(button => {
    const active = button === tab;
    button.classList.toggle('is-active', active);
    button.setAttribute('aria-selected', String(active));
  });
  page.querySelectorAll('[data-feature-panel]').forEach(panel => panel.classList.toggle('is-active', panel.dataset.featurePanel === tab.dataset.featureTab));
});

V['digital-faq'] = V.digital;
